/** Every on-screen label outside the caption track (kept here so the font loader sees all glyphs). */
export const L = {
  age: '宇宙年龄',
  year: '年',
  now: '现在',
  eras: ['原初纪元', '恒星纪元', '简并纪元', '黑洞纪元', '黑暗纪元'],
  lowS: '低熵',
  highS: '高熵',
  entropy: '熵',
  hot: '高温',
  cold: '低温',
  work: '做功',
  heatDeath: '热寂',
  heatDeathDef: '熵达到最大 · 处处热平衡 · 再无可用的能量',
  sun: '太阳系 · 我们在这里',
  horizon: '可观测宇宙边界',
  localGroup: '本星系群',
  blackDwarf: '黑矮星',
  whiteDwarf: '白矮星',
  neutron: '中子星',
  blackHole: '黑洞',
  protonDecay: '质子衰变',
  supernova: '超新星',
  redDwarf: '红矮星',
  lastStar: '最后一颗恒星',
  eventHorizon: '事件视界',
  disk: '吸积盘',
  lensing: '引力透镜',
  hawking: '霍金辐射',
  temp: '温度',
  tempMap: '温度分布',
  zoom: '放大',
  today: '今天',
  stellar: '恒星纪元',
  title: '宇宙热寂',
  credit: '画面与声音全部由代码实时生成',
  mass: '质量',
  timeLeft: '剩余寿命',
  photon: '光子',
  lepton: '轻子',
  equilibrium: '热平衡',
  maxEntropy: '最大熵',
};

export const LABEL_TEXT = JSON.stringify(L);
