"""Extract vector outlines of the few glyphs drawn with gradient fills into src/lib/glyphPaths.ts.

Chrome corrupts large gradient-filled *text* during long renders (glyphs clipped, mis-scaled or missing in the
video, while single stills look fine), so gradient titles are drawn as plain SVG paths instead.
Run after `npm run fonts` if you add characters to GLYPH_SETS:  python3 scripts/glyph-paths.py
"""
import json
import os

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
GLYPH_SETS = {
    "cn900": ("public/fonts/NotoSansSC-900.woff2", "从真空管到2亿"),
    "mono800": ("public/fonts/JetBrainsMono-800.woff2", "AI"),
}


def face(path, chars):
    font = TTFont(os.path.join(ROOT, path))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    hmtx = font["hmtx"]
    os2 = font["OS/2"]
    out = {}
    for ch in chars:
        name = cmap.get(ord(ch))
        if name is None:
            raise SystemExit(f"{path}: no glyph for {ch!r} (run npm run fonts first)")
        pen = SVGPathPen(gs)
        gs[name].draw(pen)
        out[ch] = {"adv": hmtx[name][0], "d": pen.getCommands()}
    return {
        "upm": font["head"].unitsPerEm,
        "ascent": os2.sTypoAscender,
        "descent": -os2.sTypoDescender,
        "glyphs": out,
    }


data = {k: face(p, c) for k, (p, c) in GLYPH_SETS.items()}
ts = (
    "// Generated by scripts/glyph-paths.py — do not edit.\n"
    "// Glyph outlines in font units (y up) for text that is drawn with gradient fills (see GradientText.tsx).\n"
    "export type Face = { upm: number; ascent: number; descent: number; glyphs: Record<string, { adv: number; d: string }> };\n"
    f"export const GLYPHS: Record<{' | '.join(json.dumps(k) for k in data)}, Face> = {json.dumps(data, ensure_ascii=False, indent=1)};\n"
)
with open(os.path.join(ROOT, "src/lib/glyphPaths.ts"), "w", encoding="utf8", newline="\n") as f:
    f.write(ts)
for k, v in data.items():
    print(k, "upm", v["upm"], "asc", v["ascent"], "desc", v["descent"], {c: g["adv"] for c, g in v["glyphs"].items()},
          sum(len(g["d"]) for g in v["glyphs"].values()), "path chars")
